# Done to increase the memory available to gradle.
org.gradle.jvmargs = -Xmx1G
org.gradle.parallel = true

# Java Properties
java_version = 17

# Fabric Properties
# check these on https://fabricmc.net/develop
loom_version=1.11-SNAPSHOT
minecraft_version=1.21.9
yarn_mappings=1.21.9+build.1
loader_version=0.17.2

# Dependencies
fabric_version=0.133.14+1.21.9

# Mod Properties
mod_version = 1.0.0
maven_group = com.arta.vapeaholic
archives_base_name = vapeaholic
mod_name = Vapeaholic
mod_id = vapeaholic
mod_author = Arta
mod_description = Adds Vapes in Minecraft
