# Done to increase the memory available to gradle.
org.gradle.jvmargs = -Xmx1G
org.gradle.parallel = true

# Java Properties
java_version = 17

# Fabric Properties
# check these on https://fabricmc.net/develop
loom_version=1.15-SNAPSHOT
minecraft_version=26.1
loader_version=0.18.4

# Dependencies
fabric_api_version=0.144.0+26.1

# Mod Properties
mod_version = 1.0.2
maven_group = com.arta.vapeaholic
archives_base_name = vapeaholic
mod_name = Vapeaholic
mod_id = vapeaholic
mod_author = Arta
mod_description = Adds Vapes in Minecraft
