# Done to increase the memory available to gradle.
org.gradle.jvmargs = -Xmx1G
org.gradle.parallel = true

# Java Properties
java_version = 1.8

# Forge Properties
# check on https://files.minecraftforge.net/net/minecraftforge/gradle/ForgeGradle/index.html
forge_gradle_version = 6.0.29
mappings_channel = snapshot
mappings_version = 20180814-1.12
minecraft_version = 1.12.2
# check on https://files.minecraftforge.net/net/minecraftforge/forge/index_1.12.2.html
forge_version = 14.23.5.2860

# Mod Properties
mod_version = 1.0.0
maven_group = com.arta.vapeaholic
archives_base_name = vapeaholic
mod_name = Vapeaholic
mod_id = vapeaholic
mod_author = Arta
mod_description = Adds Vapes in Minecraft
