package com.arta.vapeaholic.item;

import com.arta.vapeaholic.Vapeaholic;
import com.arta.vapeaholic.item.items.vapecomponents.*;
import com.arta.vapeaholic.item.items.vapepods.*;
import com.arta.vapeaholic.item.items.vapes.empty.*;
import com.arta.vapeaholic.item.items.vapes.water.*;
import com.arta.vapeaholic.item.items.vapes.fireresistance.*;
import com.arta.vapeaholic.item.items.vapes.instantdamage.*;
import com.arta.vapeaholic.item.items.vapes.instanthealth.*;
import com.arta.vapeaholic.item.items.vapes.invisibility.*;
import com.arta.vapeaholic.item.items.vapes.jumpboost.*;
import com.arta.vapeaholic.item.items.vapes.luck.*;
import com.arta.vapeaholic.item.items.vapes.nightvision.*;
import com.arta.vapeaholic.item.items.vapes.poison.*;
import com.arta.vapeaholic.item.items.vapes.regeneration.*;
import com.arta.vapeaholic.item.items.vapes.slowfalling.*;
import com.arta.vapeaholic.item.items.vapes.slowness.*;
import com.arta.vapeaholic.item.items.vapes.strength.*;
import com.arta.vapeaholic.item.items.vapes.swiftness.*;
import com.arta.vapeaholic.item.items.vapes.turtlemaster.*;
import com.arta.vapeaholic.item.items.vapes.waterbreathing.*;
import com.arta.vapeaholic.item.items.vapes.weakness.*;
import com.arta.vapeaholic.item.items.vapes.wither.*;

import net.minecraft.core.Registry;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.resources.Identifier;
import net.minecraft.world.item.Item;

public class ModItems {
    public static final Item BATTERY = registerItem("battery", new Battery());
    public static final Item COIL = registerItem("coil", new Coil());
    public static final Item MOUTHPIECE = registerItem("mouthpiece", new Mouthpiece());

    public static final Item VAPE_POD = registerItem("vape_pod", new VapePod());
    public static final Item WATER_VAPE_POD = registerItem("water_vape_pod", new WaterVapePod());
    public static final Item MUNDANE_VAPE_POD = registerItem("mundane_vape_pod", new MundaneVapePod());
    public static final Item THICK_VAPE_POD = registerItem("thick_vape_pod", new ThickVapePod());
    public static final Item AWKWARD_VAPE_POD = registerItem("awkward_vape_pod", new AwkwardVapePod());
    public static final Item FIRE_RESISTANCE_VAPE_POD = registerItem("fire_resistance_vape_pod", new FireResistanceVapePod());
    public static final Item INSTANT_DAMAGE_VAPE_POD = registerItem("instant_damage_vape_pod", new InstantDamageVapePod());
    public static final Item INSTANT_HEALTH_VAPE_POD = registerItem("instant_health_vape_pod", new InstantHealthVapePod());
    public static final Item INVISIBILITY_VAPE_POD = registerItem("invisibility_vape_pod", new InvisibilityVapePod());
    public static final Item JUMP_BOOST_VAPE_POD = registerItem("jump_boost_vape_pod", new JumpBoostVapePod());
    public static final Item LUCK_VAPE_POD = registerItem("luck_vape_pod", new LuckVapePod());
    public static final Item NIGHT_VISION_VAPE_POD = registerItem("night_vision_vape_pod", new NightVisionVapePod());
    public static final Item POISON_VAPE_POD = registerItem("poison_vape_pod", new PoisonVapePod());
    public static final Item REGENERATION_VAPE_POD = registerItem("regeneration_vape_pod", new RegenerationVapePod());
    public static final Item SLOW_FALLING_VAPE_POD = registerItem("slow_falling_vape_pod", new SlowFallingVapePod());
    public static final Item SLOWNESS_VAPE_POD = registerItem("slowness_vape_pod", new SlownessVapePod());
    public static final Item STRENGTH_VAPE_POD = registerItem("strength_vape_pod", new StrengthVapePod());
    public static final Item SWIFTNESS_VAPE_POD = registerItem("swiftness_vape_pod", new SwiftnessVapePod());
    public static final Item TURTLE_MASTER_VAPE_POD = registerItem("turtle_master_vape_pod", new TurtleMasterVapePod());
    public static final Item WATER_BREATHING_VAPE_POD = registerItem("water_breathing_vape_pod", new WaterBreathingVapePod());
    public static final Item WEAKNESS_VAPE_POD = registerItem("weakness_vape_pod", new WeaknessVapePod());
    public static final Item WITHER_VAPE_POD = registerItem("wither_vape_pod", new WitherVapePod());

    public static final Item RED_VAPE = registerItem("red_vape", new RedVape());
    public static final Item ORANGE_VAPE = registerItem("orange_vape", new OrangeVape());
    public static final Item YELLOW_VAPE = registerItem("yellow_vape", new YellowVape());
    public static final Item LIME_VAPE = registerItem("lime_vape", new LimeVape());
    public static final Item GREEN_VAPE = registerItem("green_vape", new GreenVape());
    public static final Item CYAN_VAPE = registerItem("cyan_vape", new CyanVape());
    public static final Item LIGHT_BLUE_VAPE = registerItem("light_blue_vape", new LightBlueVape());
    public static final Item BLUE_VAPE = registerItem("blue_vape", new BlueVape());
    public static final Item PURPLE_VAPE = registerItem("purple_vape", new PurpleVape());
    public static final Item MAGENTA_VAPE = registerItem("magenta_vape", new MagentaVape());
    public static final Item PINK_VAPE = registerItem("pink_vape", new PinkVape());
    public static final Item BROWN_VAPE = registerItem("brown_vape", new BrownVape());
    public static final Item WHITE_VAPE = registerItem("white_vape", new WhiteVape());
    public static final Item LIGHT_GRAY_VAPE = registerItem("light_gray_vape", new LightGrayVape());
    public static final Item GRAY_VAPE = registerItem("gray_vape", new GrayVape());
    public static final Item BLACK_VAPE = registerItem("black_vape", new BlackVape());

    public static final Item WATER_RED_VAPE = registerItem("water_red_vape", new WaterRedVape());
    public static final Item WATER_ORANGE_VAPE = registerItem("water_orange_vape", new WaterOrangeVape());
    public static final Item WATER_YELLOW_VAPE = registerItem("water_yellow_vape", new WaterYellowVape());
    public static final Item WATER_LIME_VAPE = registerItem("water_lime_vape", new WaterLimeVape());
    public static final Item WATER_GREEN_VAPE = registerItem("water_green_vape", new WaterGreenVape());
    public static final Item WATER_CYAN_VAPE = registerItem("water_cyan_vape", new WaterCyanVape());
    public static final Item WATER_LIGHT_BLUE_VAPE = registerItem("water_light_blue_vape", new WaterLightBlueVape());
    public static final Item WATER_BLUE_VAPE = registerItem("water_blue_vape", new WaterBlueVape());
    public static final Item WATER_PURPLE_VAPE = registerItem("water_purple_vape", new WaterPurpleVape());
    public static final Item WATER_MAGENTA_VAPE = registerItem("water_magenta_vape", new WaterMagentaVape());
    public static final Item WATER_PINK_VAPE = registerItem("water_pink_vape", new WaterPinkVape());
    public static final Item WATER_BROWN_VAPE = registerItem("water_brown_vape", new WaterBrownVape());
    public static final Item WATER_WHITE_VAPE = registerItem("water_white_vape", new WaterWhiteVape());
    public static final Item WATER_LIGHT_GRAY_VAPE = registerItem("water_light_gray_vape", new WaterLightGrayVape());
    public static final Item WATER_GRAY_VAPE = registerItem("water_gray_vape", new WaterGrayVape());
    public static final Item WATER_BLACK_VAPE = registerItem("water_black_vape", new WaterBlackVape());

    public static final Item FIRE_RESISTANCE_RED_VAPE = registerItem("fire_resistance_red_vape", new FireResistanceRedVape());
    public static final Item FIRE_RESISTANCE_ORANGE_VAPE = registerItem("fire_resistance_orange_vape", new FireResistanceOrangeVape());
    public static final Item FIRE_RESISTANCE_YELLOW_VAPE = registerItem("fire_resistance_yellow_vape", new FireResistanceYellowVape());
    public static final Item FIRE_RESISTANCE_LIME_VAPE = registerItem("fire_resistance_lime_vape", new FireResistanceLimeVape());
    public static final Item FIRE_RESISTANCE_GREEN_VAPE = registerItem("fire_resistance_green_vape", new FireResistanceGreenVape());
    public static final Item FIRE_RESISTANCE_CYAN_VAPE = registerItem("fire_resistance_cyan_vape", new FireResistanceCyanVape());
    public static final Item FIRE_RESISTANCE_LIGHT_BLUE_VAPE = registerItem("fire_resistance_light_blue_vape", new FireResistanceLightBlueVape());
    public static final Item FIRE_RESISTANCE_BLUE_VAPE = registerItem("fire_resistance_blue_vape", new FireResistanceBlueVape());
    public static final Item FIRE_RESISTANCE_PURPLE_VAPE = registerItem("fire_resistance_purple_vape", new FireResistancePurpleVape());
    public static final Item FIRE_RESISTANCE_MAGENTA_VAPE = registerItem("fire_resistance_magenta_vape", new FireResistanceMagentaVape());
    public static final Item FIRE_RESISTANCE_PINK_VAPE = registerItem("fire_resistance_pink_vape", new FireResistancePinkVape());
    public static final Item FIRE_RESISTANCE_BROWN_VAPE = registerItem("fire_resistance_brown_vape", new FireResistanceBrownVape());
    public static final Item FIRE_RESISTANCE_WHITE_VAPE = registerItem("fire_resistance_white_vape", new FireResistanceWhiteVape());
    public static final Item FIRE_RESISTANCE_LIGHT_GRAY_VAPE = registerItem("fire_resistance_light_gray_vape", new FireResistanceLightGrayVape());
    public static final Item FIRE_RESISTANCE_GRAY_VAPE = registerItem("fire_resistance_gray_vape", new FireResistanceGrayVape());
    public static final Item FIRE_RESISTANCE_BLACK_VAPE = registerItem("fire_resistance_black_vape", new FireResistanceBlackVape());

    public static final Item INSTANT_DAMAGE_RED_VAPE = registerItem("instant_damage_red_vape", new InstantDamageRedVape());
    public static final Item INSTANT_DAMAGE_ORANGE_VAPE = registerItem("instant_damage_orange_vape", new InstantDamageOrangeVape());
    public static final Item INSTANT_DAMAGE_YELLOW_VAPE = registerItem("instant_damage_yellow_vape", new InstantDamageYellowVape());
    public static final Item INSTANT_DAMAGE_LIME_VAPE = registerItem("instant_damage_lime_vape", new InstantDamageLimeVape());
    public static final Item INSTANT_DAMAGE_GREEN_VAPE = registerItem("instant_damage_green_vape", new InstantDamageGreenVape());
    public static final Item INSTANT_DAMAGE_CYAN_VAPE = registerItem("instant_damage_cyan_vape", new InstantDamageCyanVape());
    public static final Item INSTANT_DAMAGE_LIGHT_BLUE_VAPE = registerItem("instant_damage_light_blue_vape", new InstantDamageLightBlueVape());
    public static final Item INSTANT_DAMAGE_BLUE_VAPE = registerItem("instant_damage_blue_vape", new InstantDamageBlueVape());
    public static final Item INSTANT_DAMAGE_PURPLE_VAPE = registerItem("instant_damage_purple_vape", new InstantDamagePurpleVape());
    public static final Item INSTANT_DAMAGE_MAGENTA_VAPE = registerItem("instant_damage_magenta_vape", new InstantDamageMagentaVape());
    public static final Item INSTANT_DAMAGE_PINK_VAPE = registerItem("instant_damage_pink_vape", new InstantDamagePinkVape());
    public static final Item INSTANT_DAMAGE_BROWN_VAPE = registerItem("instant_damage_brown_vape", new InstantDamageBrownVape());
    public static final Item INSTANT_DAMAGE_WHITE_VAPE = registerItem("instant_damage_white_vape", new InstantDamageWhiteVape());
    public static final Item INSTANT_DAMAGE_LIGHT_GRAY_VAPE = registerItem("instant_damage_light_gray_vape", new InstantDamageLightGrayVape());
    public static final Item INSTANT_DAMAGE_GRAY_VAPE = registerItem("instant_damage_gray_vape", new InstantDamageGrayVape());
    public static final Item INSTANT_DAMAGE_BLACK_VAPE = registerItem("instant_damage_black_vape", new InstantDamageBlackVape());

    public static final Item INSTANT_HEALTH_RED_VAPE = registerItem("instant_health_red_vape", new InstantHealthRedVape());
    public static final Item INSTANT_HEALTH_ORANGE_VAPE = registerItem("instant_health_orange_vape", new InstantHealthOrangeVape());
    public static final Item INSTANT_HEALTH_YELLOW_VAPE = registerItem("instant_health_yellow_vape", new InstantHealthYellowVape());
    public static final Item INSTANT_HEALTH_LIME_VAPE = registerItem("instant_health_lime_vape", new InstantHealthLimeVape());
    public static final Item INSTANT_HEALTH_GREEN_VAPE = registerItem("instant_health_green_vape", new InstantHealthGreenVape());
    public static final Item INSTANT_HEALTH_CYAN_VAPE = registerItem("instant_health_cyan_vape", new InstantHealthCyanVape());
    public static final Item INSTANT_HEALTH_LIGHT_BLUE_VAPE = registerItem("instant_health_light_blue_vape", new InstantHealthLightBlueVape());
    public static final Item INSTANT_HEALTH_BLUE_VAPE = registerItem("instant_health_blue_vape", new InstantHealthBlueVape());
    public static final Item INSTANT_HEALTH_PURPLE_VAPE = registerItem("instant_health_purple_vape", new InstantHealthPurpleVape());
    public static final Item INSTANT_HEALTH_MAGENTA_VAPE = registerItem("instant_health_magenta_vape", new InstantHealthMagentaVape());
    public static final Item INSTANT_HEALTH_PINK_VAPE = registerItem("instant_health_pink_vape", new InstantHealthPinkVape());
    public static final Item INSTANT_HEALTH_BROWN_VAPE = registerItem("instant_health_brown_vape", new InstantHealthBrownVape());
    public static final Item INSTANT_HEALTH_WHITE_VAPE = registerItem("instant_health_white_vape", new InstantHealthWhiteVape());
    public static final Item INSTANT_HEALTH_LIGHT_GRAY_VAPE = registerItem("instant_health_light_gray_vape", new InstantHealthLightGrayVape());
    public static final Item INSTANT_HEALTH_GRAY_VAPE = registerItem("instant_health_gray_vape", new InstantHealthGrayVape());
    public static final Item INSTANT_HEALTH_BLACK_VAPE = registerItem("instant_health_black_vape", new InstantHealthBlackVape());

    public static final Item INVISIBILITY_RED_VAPE = registerItem("invisibility_red_vape", new InvisibilityRedVape());
    public static final Item INVISIBILITY_ORANGE_VAPE = registerItem("invisibility_orange_vape", new InvisibilityOrangeVape());
    public static final Item INVISIBILITY_YELLOW_VAPE = registerItem("invisibility_yellow_vape", new InvisibilityYellowVape());
    public static final Item INVISIBILITY_LIME_VAPE = registerItem("invisibility_lime_vape", new InvisibilityLimeVape());
    public static final Item INVISIBILITY_GREEN_VAPE = registerItem("invisibility_green_vape", new InvisibilityGreenVape());
    public static final Item INVISIBILITY_CYAN_VAPE = registerItem("invisibility_cyan_vape", new InvisibilityCyanVape());
    public static final Item INVISIBILITY_LIGHT_BLUE_VAPE = registerItem("invisibility_light_blue_vape", new InvisibilityLightBlueVape());
    public static final Item INVISIBILITY_BLUE_VAPE = registerItem("invisibility_blue_vape", new InvisibilityBlueVape());
    public static final Item INVISIBILITY_PURPLE_VAPE = registerItem("invisibility_purple_vape", new InvisibilityPurpleVape());
    public static final Item INVISIBILITY_MAGENTA_VAPE = registerItem("invisibility_magenta_vape", new InvisibilityMagentaVape());
    public static final Item INVISIBILITY_PINK_VAPE = registerItem("invisibility_pink_vape", new InvisibilityPinkVape());
    public static final Item INVISIBILITY_BROWN_VAPE = registerItem("invisibility_brown_vape", new InvisibilityBrownVape());
    public static final Item INVISIBILITY_WHITE_VAPE = registerItem("invisibility_white_vape", new InvisibilityWhiteVape());
    public static final Item INVISIBILITY_LIGHT_GRAY_VAPE = registerItem("invisibility_light_gray_vape", new InvisibilityLightGrayVape());
    public static final Item INVISIBILITY_GRAY_VAPE = registerItem("invisibility_gray_vape", new InvisibilityGrayVape());
    public static final Item INVISIBILITY_BLACK_VAPE = registerItem("invisibility_black_vape", new InvisibilityBlackVape());

    public static final Item JUMP_BOOST_RED_VAPE = registerItem("jump_boost_red_vape", new JumpBoostRedVape());
    public static final Item JUMP_BOOST_ORANGE_VAPE = registerItem("jump_boost_orange_vape", new JumpBoostOrangeVape());
    public static final Item JUMP_BOOST_YELLOW_VAPE = registerItem("jump_boost_yellow_vape", new JumpBoostYellowVape());
    public static final Item JUMP_BOOST_LIME_VAPE = registerItem("jump_boost_lime_vape", new JumpBoostLimeVape());
    public static final Item JUMP_BOOST_GREEN_VAPE = registerItem("jump_boost_green_vape", new JumpBoostGreenVape());
    public static final Item JUMP_BOOST_CYAN_VAPE = registerItem("jump_boost_cyan_vape", new JumpBoostCyanVape());
    public static final Item JUMP_BOOST_LIGHT_BLUE_VAPE = registerItem("jump_boost_light_blue_vape", new JumpBoostLightBlueVape());
    public static final Item JUMP_BOOST_BLUE_VAPE = registerItem("jump_boost_blue_vape", new JumpBoostBlueVape());
    public static final Item JUMP_BOOST_PURPLE_VAPE = registerItem("jump_boost_purple_vape", new JumpBoostPurpleVape());
    public static final Item JUMP_BOOST_MAGENTA_VAPE = registerItem("jump_boost_magenta_vape", new JumpBoostMagentaVape());
    public static final Item JUMP_BOOST_PINK_VAPE = registerItem("jump_boost_pink_vape", new JumpBoostPinkVape());
    public static final Item JUMP_BOOST_BROWN_VAPE = registerItem("jump_boost_brown_vape", new JumpBoostBrownVape());
    public static final Item JUMP_BOOST_WHITE_VAPE = registerItem("jump_boost_white_vape", new JumpBoostWhiteVape());
    public static final Item JUMP_BOOST_LIGHT_GRAY_VAPE = registerItem("jump_boost_light_gray_vape", new JumpBoostLightGrayVape());
    public static final Item JUMP_BOOST_GRAY_VAPE = registerItem("jump_boost_gray_vape", new JumpBoostGrayVape());
    public static final Item JUMP_BOOST_BLACK_VAPE = registerItem("jump_boost_black_vape", new JumpBoostBlackVape());

    public static final Item LUCK_RED_VAPE = registerItem("luck_red_vape", new LuckRedVape());
    public static final Item LUCK_ORANGE_VAPE = registerItem("luck_orange_vape", new LuckOrangeVape());
    public static final Item LUCK_YELLOW_VAPE = registerItem("luck_yellow_vape", new LuckYellowVape());
    public static final Item LUCK_LIME_VAPE = registerItem("luck_lime_vape", new LuckLimeVape());
    public static final Item LUCK_GREEN_VAPE = registerItem("luck_green_vape", new LuckGreenVape());
    public static final Item LUCK_CYAN_VAPE = registerItem("luck_cyan_vape", new LuckCyanVape());
    public static final Item LUCK_LIGHT_BLUE_VAPE = registerItem("luck_light_blue_vape", new LuckLightBlueVape());
    public static final Item LUCK_BLUE_VAPE = registerItem("luck_blue_vape", new LuckBlueVape());
    public static final Item LUCK_PURPLE_VAPE = registerItem("luck_purple_vape", new LuckPurpleVape());
    public static final Item LUCK_MAGENTA_VAPE = registerItem("luck_magenta_vape", new LuckMagentaVape());
    public static final Item LUCK_PINK_VAPE = registerItem("luck_pink_vape", new LuckPinkVape());
    public static final Item LUCK_BROWN_VAPE = registerItem("luck_brown_vape", new LuckBrownVape());
    public static final Item LUCK_WHITE_VAPE = registerItem("luck_white_vape", new LuckWhiteVape());
    public static final Item LUCK_LIGHT_GRAY_VAPE = registerItem("luck_light_gray_vape", new LuckLightGrayVape());
    public static final Item LUCK_GRAY_VAPE = registerItem("luck_gray_vape", new LuckGrayVape());
    public static final Item LUCK_BLACK_VAPE = registerItem("luck_black_vape", new LuckBlackVape());

    public static final Item NIGHT_VISION_RED_VAPE = registerItem("night_vision_red_vape", new NightVisionRedVape());
    public static final Item NIGHT_VISION_ORANGE_VAPE = registerItem("night_vision_orange_vape", new NightVisionOrangeVape());
    public static final Item NIGHT_VISION_YELLOW_VAPE = registerItem("night_vision_yellow_vape", new NightVisionYellowVape());
    public static final Item NIGHT_VISION_LIME_VAPE = registerItem("night_vision_lime_vape", new NightVisionLimeVape());
    public static final Item NIGHT_VISION_GREEN_VAPE = registerItem("night_vision_green_vape", new NightVisionGreenVape());
    public static final Item NIGHT_VISION_CYAN_VAPE = registerItem("night_vision_cyan_vape", new NightVisionCyanVape());
    public static final Item NIGHT_VISION_LIGHT_BLUE_VAPE = registerItem("night_vision_light_blue_vape", new NightVisionLightBlueVape());
    public static final Item NIGHT_VISION_BLUE_VAPE = registerItem("night_vision_blue_vape", new NightVisionBlueVape());
    public static final Item NIGHT_VISION_PURPLE_VAPE = registerItem("night_vision_purple_vape", new NightVisionPurpleVape());
    public static final Item NIGHT_VISION_MAGENTA_VAPE = registerItem("night_vision_magenta_vape", new NightVisionMagentaVape());
    public static final Item NIGHT_VISION_PINK_VAPE = registerItem("night_vision_pink_vape", new NightVisionPinkVape());
    public static final Item NIGHT_VISION_BROWN_VAPE = registerItem("night_vision_brown_vape", new NightVisionBrownVape());
    public static final Item NIGHT_VISION_WHITE_VAPE = registerItem("night_vision_white_vape", new NightVisionWhiteVape());
    public static final Item NIGHT_VISION_LIGHT_GRAY_VAPE = registerItem("night_vision_light_gray_vape", new NightVisionLightGrayVape());
    public static final Item NIGHT_VISION_GRAY_VAPE = registerItem("night_vision_gray_vape", new NightVisionGrayVape());
    public static final Item NIGHT_VISION_BLACK_VAPE = registerItem("night_vision_black_vape", new NightVisionBlackVape());

    public static final Item POISON_RED_VAPE = registerItem("poison_red_vape", new PoisonRedVape());
    public static final Item POISON_ORANGE_VAPE = registerItem("poison_orange_vape", new PoisonOrangeVape());
    public static final Item POISON_YELLOW_VAPE = registerItem("poison_yellow_vape", new PoisonYellowVape());
    public static final Item POISON_LIME_VAPE = registerItem("poison_lime_vape", new PoisonLimeVape());
    public static final Item POISON_GREEN_VAPE = registerItem("poison_green_vape", new PoisonGreenVape());
    public static final Item POISON_CYAN_VAPE = registerItem("poison_cyan_vape", new PoisonCyanVape());
    public static final Item POISON_LIGHT_BLUE_VAPE = registerItem("poison_light_blue_vape", new PoisonLightBlueVape());
    public static final Item POISON_BLUE_VAPE = registerItem("poison_blue_vape", new PoisonBlueVape());
    public static final Item POISON_PURPLE_VAPE = registerItem("poison_purple_vape", new PoisonPurpleVape());
    public static final Item POISON_MAGENTA_VAPE = registerItem("poison_magenta_vape", new PoisonMagentaVape());
    public static final Item POISON_PINK_VAPE = registerItem("poison_pink_vape", new PoisonPinkVape());
    public static final Item POISON_BROWN_VAPE = registerItem("poison_brown_vape", new PoisonBrownVape());
    public static final Item POISON_WHITE_VAPE = registerItem("poison_white_vape", new PoisonWhiteVape());
    public static final Item POISON_LIGHT_GRAY_VAPE = registerItem("poison_light_gray_vape", new PoisonLightGrayVape());
    public static final Item POISON_GRAY_VAPE = registerItem("poison_gray_vape", new PoisonGrayVape());
    public static final Item POISON_BLACK_VAPE = registerItem("poison_black_vape", new PoisonBlackVape());

    public static final Item REGENERATION_RED_VAPE = registerItem("regeneration_red_vape", new RegenerationRedVape());
    public static final Item REGENERATION_ORANGE_VAPE = registerItem("regeneration_orange_vape", new RegenerationOrangeVape());
    public static final Item REGENERATION_YELLOW_VAPE = registerItem("regeneration_yellow_vape", new RegenerationYellowVape());
    public static final Item REGENERATION_LIME_VAPE = registerItem("regeneration_lime_vape", new RegenerationLimeVape());
    public static final Item REGENERATION_GREEN_VAPE = registerItem("regeneration_green_vape", new RegenerationGreenVape());
    public static final Item REGENERATION_CYAN_VAPE = registerItem("regeneration_cyan_vape", new RegenerationCyanVape());
    public static final Item REGENERATION_LIGHT_BLUE_VAPE = registerItem("regeneration_light_blue_vape", new RegenerationLightBlueVape());
    public static final Item REGENERATION_BLUE_VAPE = registerItem("regeneration_blue_vape", new RegenerationBlueVape());
    public static final Item REGENERATION_PURPLE_VAPE = registerItem("regeneration_purple_vape", new RegenerationPurpleVape());
    public static final Item REGENERATION_MAGENTA_VAPE = registerItem("regeneration_magenta_vape", new RegenerationMagentaVape());
    public static final Item REGENERATION_PINK_VAPE = registerItem("regeneration_pink_vape", new RegenerationPinkVape());
    public static final Item REGENERATION_BROWN_VAPE = registerItem("regeneration_brown_vape", new RegenerationBrownVape());
    public static final Item REGENERATION_WHITE_VAPE = registerItem("regeneration_white_vape", new RegenerationWhiteVape());
    public static final Item REGENERATION_LIGHT_GRAY_VAPE = registerItem("regeneration_light_gray_vape", new RegenerationLightGrayVape());
    public static final Item REGENERATION_GRAY_VAPE = registerItem("regeneration_gray_vape", new RegenerationGrayVape());
    public static final Item REGENERATION_BLACK_VAPE = registerItem("regeneration_black_vape", new RegenerationBlackVape());

    public static final Item SLOW_FALLING_RED_VAPE = registerItem("slow_falling_red_vape", new SlowFallingRedVape());
    public static final Item SLOW_FALLING_ORANGE_VAPE = registerItem("slow_falling_orange_vape", new SlowFallingOrangeVape());
    public static final Item SLOW_FALLING_YELLOW_VAPE = registerItem("slow_falling_yellow_vape", new SlowFallingYellowVape());
    public static final Item SLOW_FALLING_LIME_VAPE = registerItem("slow_falling_lime_vape", new SlowFallingLimeVape());
    public static final Item SLOW_FALLING_GREEN_VAPE = registerItem("slow_falling_green_vape", new SlowFallingGreenVape());
    public static final Item SLOW_FALLING_CYAN_VAPE = registerItem("slow_falling_cyan_vape", new SlowFallingCyanVape());
    public static final Item SLOW_FALLING_LIGHT_BLUE_VAPE = registerItem("slow_falling_light_blue_vape", new SlowFallingLightBlueVape());
    public static final Item SLOW_FALLING_BLUE_VAPE = registerItem("slow_falling_blue_vape", new SlowFallingBlueVape());
    public static final Item SLOW_FALLING_PURPLE_VAPE = registerItem("slow_falling_purple_vape", new SlowFallingPurpleVape());
    public static final Item SLOW_FALLING_MAGENTA_VAPE = registerItem("slow_falling_magenta_vape", new SlowFallingMagentaVape());
    public static final Item SLOW_FALLING_PINK_VAPE = registerItem("slow_falling_pink_vape", new SlowFallingPinkVape());
    public static final Item SLOW_FALLING_BROWN_VAPE = registerItem("slow_falling_brown_vape", new SlowFallingBrownVape());
    public static final Item SLOW_FALLING_WHITE_VAPE = registerItem("slow_falling_white_vape", new SlowFallingWhiteVape());
    public static final Item SLOW_FALLING_LIGHT_GRAY_VAPE = registerItem("slow_falling_light_gray_vape", new SlowFallingLightGrayVape());
    public static final Item SLOW_FALLING_GRAY_VAPE = registerItem("slow_falling_gray_vape", new SlowFallingGrayVape());
    public static final Item SLOW_FALLING_BLACK_VAPE = registerItem("slow_falling_black_vape", new SlowFallingBlackVape());

    public static final Item SLOWNESS_RED_VAPE = registerItem("slowness_red_vape", new SlownessRedVape());
    public static final Item SLOWNESS_ORANGE_VAPE = registerItem("slowness_orange_vape", new SlownessOrangeVape());
    public static final Item SLOWNESS_YELLOW_VAPE = registerItem("slowness_yellow_vape", new SlownessYellowVape());
    public static final Item SLOWNESS_LIME_VAPE = registerItem("slowness_lime_vape", new SlownessLimeVape());
    public static final Item SLOWNESS_GREEN_VAPE = registerItem("slowness_green_vape", new SlownessGreenVape());
    public static final Item SLOWNESS_CYAN_VAPE = registerItem("slowness_cyan_vape", new SlownessCyanVape());
    public static final Item SLOWNESS_LIGHT_BLUE_VAPE = registerItem("slowness_light_blue_vape", new SlownessLightBlueVape());
    public static final Item SLOWNESS_BLUE_VAPE = registerItem("slowness_blue_vape", new SlownessBlueVape());
    public static final Item SLOWNESS_PURPLE_VAPE = registerItem("slowness_purple_vape", new SlownessPurpleVape());
    public static final Item SLOWNESS_MAGENTA_VAPE = registerItem("slowness_magenta_vape", new SlownessMagentaVape());
    public static final Item SLOWNESS_PINK_VAPE = registerItem("slowness_pink_vape", new SlownessPinkVape());
    public static final Item SLOWNESS_BROWN_VAPE = registerItem("slowness_brown_vape", new SlownessBrownVape());
    public static final Item SLOWNESS_WHITE_VAPE = registerItem("slowness_white_vape", new SlownessWhiteVape());
    public static final Item SLOWNESS_LIGHT_GRAY_VAPE = registerItem("slowness_light_gray_vape", new SlownessLightGrayVape());
    public static final Item SLOWNESS_GRAY_VAPE = registerItem("slowness_gray_vape", new SlownessGrayVape());
    public static final Item SLOWNESS_BLACK_VAPE = registerItem("slowness_black_vape", new SlownessBlackVape());

    public static final Item STRENGTH_RED_VAPE = registerItem("strength_red_vape", new StrengthRedVape());
    public static final Item STRENGTH_ORANGE_VAPE = registerItem("strength_orange_vape", new StrengthOrangeVape());
    public static final Item STRENGTH_YELLOW_VAPE = registerItem("strength_yellow_vape", new StrengthYellowVape());
    public static final Item STRENGTH_LIME_VAPE = registerItem("strength_lime_vape", new StrengthLimeVape());
    public static final Item STRENGTH_GREEN_VAPE = registerItem("strength_green_vape", new StrengthGreenVape());
    public static final Item STRENGTH_CYAN_VAPE = registerItem("strength_cyan_vape", new StrengthCyanVape());
    public static final Item STRENGTH_LIGHT_BLUE_VAPE = registerItem("strength_light_blue_vape", new StrengthLightBlueVape());
    public static final Item STRENGTH_BLUE_VAPE = registerItem("strength_blue_vape", new StrengthBlueVape());
    public static final Item STRENGTH_PURPLE_VAPE = registerItem("strength_purple_vape", new StrengthPurpleVape());
    public static final Item STRENGTH_MAGENTA_VAPE = registerItem("strength_magenta_vape", new StrengthMagentaVape());
    public static final Item STRENGTH_PINK_VAPE = registerItem("strength_pink_vape", new StrengthPinkVape());
    public static final Item STRENGTH_BROWN_VAPE = registerItem("strength_brown_vape", new StrengthBrownVape());
    public static final Item STRENGTH_WHITE_VAPE = registerItem("strength_white_vape", new StrengthWhiteVape());
    public static final Item STRENGTH_LIGHT_GRAY_VAPE = registerItem("strength_light_gray_vape", new StrengthLightGrayVape());
    public static final Item STRENGTH_GRAY_VAPE = registerItem("strength_gray_vape", new StrengthGrayVape());
    public static final Item STRENGTH_BLACK_VAPE = registerItem("strength_black_vape", new StrengthBlackVape());

    public static final Item SWIFTNESS_RED_VAPE = registerItem("swiftness_red_vape", new SwiftnessRedVape());
    public static final Item SWIFTNESS_ORANGE_VAPE = registerItem("swiftness_orange_vape", new SwiftnessOrangeVape());
    public static final Item SWIFTNESS_YELLOW_VAPE = registerItem("swiftness_yellow_vape", new SwiftnessYellowVape());
    public static final Item SWIFTNESS_LIME_VAPE = registerItem("swiftness_lime_vape", new SwiftnessLimeVape());
    public static final Item SWIFTNESS_GREEN_VAPE = registerItem("swiftness_green_vape", new SwiftnessGreenVape());
    public static final Item SWIFTNESS_CYAN_VAPE = registerItem("swiftness_cyan_vape", new SwiftnessCyanVape());
    public static final Item SWIFTNESS_LIGHT_BLUE_VAPE = registerItem("swiftness_light_blue_vape", new SwiftnessLightBlueVape());
    public static final Item SWIFTNESS_BLUE_VAPE = registerItem("swiftness_blue_vape", new SwiftnessBlueVape());
    public static final Item SWIFTNESS_PURPLE_VAPE = registerItem("swiftness_purple_vape", new SwiftnessPurpleVape());
    public static final Item SWIFTNESS_MAGENTA_VAPE = registerItem("swiftness_magenta_vape", new SwiftnessMagentaVape());
    public static final Item SWIFTNESS_PINK_VAPE = registerItem("swiftness_pink_vape", new SwiftnessPinkVape());
    public static final Item SWIFTNESS_BROWN_VAPE = registerItem("swiftness_brown_vape", new SwiftnessBrownVape());
    public static final Item SWIFTNESS_WHITE_VAPE = registerItem("swiftness_white_vape", new SwiftnessWhiteVape());
    public static final Item SWIFTNESS_LIGHT_GRAY_VAPE = registerItem("swiftness_light_gray_vape", new SwiftnessLightGrayVape());
    public static final Item SWIFTNESS_GRAY_VAPE = registerItem("swiftness_gray_vape", new SwiftnessGrayVape());
    public static final Item SWIFTNESS_BLACK_VAPE = registerItem("swiftness_black_vape", new SwiftnessBlackVape());

    public static final Item TURTLE_MASTER_RED_VAPE = registerItem("turtle_master_red_vape", new TurtleMasterRedVape());
    public static final Item TURTLE_MASTER_ORANGE_VAPE = registerItem("turtle_master_orange_vape", new TurtleMasterOrangeVape());
    public static final Item TURTLE_MASTER_YELLOW_VAPE = registerItem("turtle_master_yellow_vape", new TurtleMasterYellowVape());
    public static final Item TURTLE_MASTER_LIME_VAPE = registerItem("turtle_master_lime_vape", new TurtleMasterLimeVape());
    public static final Item TURTLE_MASTER_GREEN_VAPE = registerItem("turtle_master_green_vape", new TurtleMasterGreenVape());
    public static final Item TURTLE_MASTER_CYAN_VAPE = registerItem("turtle_master_cyan_vape", new TurtleMasterCyanVape());
    public static final Item TURTLE_MASTER_LIGHT_BLUE_VAPE = registerItem("turtle_master_light_blue_vape", new TurtleMasterLightBlueVape());
    public static final Item TURTLE_MASTER_BLUE_VAPE = registerItem("turtle_master_blue_vape", new TurtleMasterBlueVape());
    public static final Item TURTLE_MASTER_PURPLE_VAPE = registerItem("turtle_master_purple_vape", new TurtleMasterPurpleVape());
    public static final Item TURTLE_MASTER_MAGENTA_VAPE = registerItem("turtle_master_magenta_vape", new TurtleMasterMagentaVape());
    public static final Item TURTLE_MASTER_PINK_VAPE = registerItem("turtle_master_pink_vape", new TurtleMasterPinkVape());
    public static final Item TURTLE_MASTER_BROWN_VAPE = registerItem("turtle_master_brown_vape", new TurtleMasterBrownVape());
    public static final Item TURTLE_MASTER_WHITE_VAPE = registerItem("turtle_master_white_vape", new TurtleMasterWhiteVape());
    public static final Item TURTLE_MASTER_LIGHT_GRAY_VAPE = registerItem("turtle_master_light_gray_vape", new TurtleMasterLightGrayVape());
    public static final Item TURTLE_MASTER_GRAY_VAPE = registerItem("turtle_master_gray_vape", new TurtleMasterGrayVape());
    public static final Item TURTLE_MASTER_BLACK_VAPE = registerItem("turtle_master_black_vape", new TurtleMasterBlackVape());

    public static final Item WATER_BREATHING_RED_VAPE = registerItem("water_breathing_red_vape", new WaterBreathingRedVape());
    public static final Item WATER_BREATHING_ORANGE_VAPE = registerItem("water_breathing_orange_vape", new WaterBreathingOrangeVape());
    public static final Item WATER_BREATHING_YELLOW_VAPE = registerItem("water_breathing_yellow_vape", new WaterBreathingYellowVape());
    public static final Item WATER_BREATHING_LIME_VAPE = registerItem("water_breathing_lime_vape", new WaterBreathingLimeVape());
    public static final Item WATER_BREATHING_GREEN_VAPE = registerItem("water_breathing_green_vape", new WaterBreathingGreenVape());
    public static final Item WATER_BREATHING_CYAN_VAPE = registerItem("water_breathing_cyan_vape", new WaterBreathingCyanVape());
    public static final Item WATER_BREATHING_LIGHT_BLUE_VAPE = registerItem("water_breathing_light_blue_vape", new WaterBreathingLightBlueVape());
    public static final Item WATER_BREATHING_BLUE_VAPE = registerItem("water_breathing_blue_vape", new WaterBreathingBlueVape());
    public static final Item WATER_BREATHING_PURPLE_VAPE = registerItem("water_breathing_purple_vape", new WaterBreathingPurpleVape());
    public static final Item WATER_BREATHING_MAGENTA_VAPE = registerItem("water_breathing_magenta_vape", new WaterBreathingMagentaVape());
    public static final Item WATER_BREATHING_PINK_VAPE = registerItem("water_breathing_pink_vape", new WaterBreathingPinkVape());
    public static final Item WATER_BREATHING_BROWN_VAPE = registerItem("water_breathing_brown_vape", new WaterBreathingBrownVape());
    public static final Item WATER_BREATHING_WHITE_VAPE = registerItem("water_breathing_white_vape", new WaterBreathingWhiteVape());
    public static final Item WATER_BREATHING_LIGHT_GRAY_VAPE = registerItem("water_breathing_light_gray_vape", new WaterBreathingLightGrayVape());
    public static final Item WATER_BREATHING_GRAY_VAPE = registerItem("water_breathing_gray_vape", new WaterBreathingGrayVape());
    public static final Item WATER_BREATHING_BLACK_VAPE = registerItem("water_breathing_black_vape", new WaterBreathingBlackVape());

    public static final Item WEAKNESS_RED_VAPE = registerItem("weakness_red_vape", new WeaknessRedVape());
    public static final Item WEAKNESS_ORANGE_VAPE = registerItem("weakness_orange_vape", new WeaknessOrangeVape());
    public static final Item WEAKNESS_YELLOW_VAPE = registerItem("weakness_yellow_vape", new WeaknessYellowVape());
    public static final Item WEAKNESS_LIME_VAPE = registerItem("weakness_lime_vape", new WeaknessLimeVape());
    public static final Item WEAKNESS_GREEN_VAPE = registerItem("weakness_green_vape", new WeaknessGreenVape());
    public static final Item WEAKNESS_CYAN_VAPE = registerItem("weakness_cyan_vape", new WeaknessCyanVape());
    public static final Item WEAKNESS_LIGHT_BLUE_VAPE = registerItem("weakness_light_blue_vape", new WeaknessLightBlueVape());
    public static final Item WEAKNESS_BLUE_VAPE = registerItem("weakness_blue_vape", new WeaknessBlueVape());
    public static final Item WEAKNESS_PURPLE_VAPE = registerItem("weakness_purple_vape", new WeaknessPurpleVape());
    public static final Item WEAKNESS_MAGENTA_VAPE = registerItem("weakness_magenta_vape", new WeaknessMagentaVape());
    public static final Item WEAKNESS_PINK_VAPE = registerItem("weakness_pink_vape", new WeaknessPinkVape());
    public static final Item WEAKNESS_BROWN_VAPE = registerItem("weakness_brown_vape", new WeaknessBrownVape());
    public static final Item WEAKNESS_WHITE_VAPE = registerItem("weakness_white_vape", new WeaknessWhiteVape());
    public static final Item WEAKNESS_LIGHT_GRAY_VAPE = registerItem("weakness_light_gray_vape", new WeaknessLightGrayVape());
    public static final Item WEAKNESS_GRAY_VAPE = registerItem("weakness_gray_vape", new WeaknessGrayVape());
    public static final Item WEAKNESS_BLACK_VAPE = registerItem("weakness_black_vape", new WeaknessBlackVape());

    public static final Item WITHER_RED_VAPE = registerItem("wither_red_vape", new WitherRedVape());
    public static final Item WITHER_ORANGE_VAPE = registerItem("wither_orange_vape", new WitherOrangeVape());
    public static final Item WITHER_YELLOW_VAPE = registerItem("wither_yellow_vape", new WitherYellowVape());
    public static final Item WITHER_LIME_VAPE = registerItem("wither_lime_vape", new WitherLimeVape());
    public static final Item WITHER_GREEN_VAPE = registerItem("wither_green_vape", new WitherGreenVape());
    public static final Item WITHER_CYAN_VAPE = registerItem("wither_cyan_vape", new WitherCyanVape());
    public static final Item WITHER_LIGHT_BLUE_VAPE = registerItem("wither_light_blue_vape", new WitherLightBlueVape());
    public static final Item WITHER_BLUE_VAPE = registerItem("wither_blue_vape", new WitherBlueVape());
    public static final Item WITHER_PURPLE_VAPE = registerItem("wither_purple_vape", new WitherPurpleVape());
    public static final Item WITHER_MAGENTA_VAPE = registerItem("wither_magenta_vape", new WitherMagentaVape());
    public static final Item WITHER_PINK_VAPE = registerItem("wither_pink_vape", new WitherPinkVape());
    public static final Item WITHER_BROWN_VAPE = registerItem("wither_brown_vape", new WitherBrownVape());
    public static final Item WITHER_WHITE_VAPE = registerItem("wither_white_vape", new WitherWhiteVape());
    public static final Item WITHER_LIGHT_GRAY_VAPE = registerItem("wither_light_gray_vape", new WitherLightGrayVape());
    public static final Item WITHER_GRAY_VAPE = registerItem("wither_gray_vape", new WitherGrayVape());
    public static final Item WITHER_BLACK_VAPE = registerItem("wither_black_vape", new WitherBlackVape());



    private static Item registerItem(String name, Item item) {
        return Registry.register(BuiltInRegistries.ITEM, Identifier.fromNamespaceAndPath(Vapeaholic.MOD_ID, name), item);
    }

    public static void registerModItems() {
        Vapeaholic.LOGGER.info("Registering Mod Items for " + Vapeaholic.MOD_ID);
    }
}
