package com.arta.vapeaholic.item;

import com.arta.vapeaholic.Vapeaholic;
import com.arta.vapeaholic.item.items.vapecomponents.*;
import com.arta.vapeaholic.item.items.vapepods.*;
import com.arta.vapeaholic.item.items.vapes.empty.*;
import com.arta.vapeaholic.item.items.vapes.water.*;
import com.arta.vapeaholic.item.items.vapes.fireresistance.*;
import com.arta.vapeaholic.item.items.vapes.instantdamage.*;
import com.arta.vapeaholic.item.items.vapes.instanthealth.*;
import com.arta.vapeaholic.item.items.vapes.invisibility.*;
import com.arta.vapeaholic.item.items.vapes.jumpboost.*;
import com.arta.vapeaholic.item.items.vapes.luck.*;
import com.arta.vapeaholic.item.items.vapes.nightvision.*;
import com.arta.vapeaholic.item.items.vapes.poison.*;
import com.arta.vapeaholic.item.items.vapes.regeneration.*;
import com.arta.vapeaholic.item.items.vapes.slowness.*;
import com.arta.vapeaholic.item.items.vapes.strength.*;
import com.arta.vapeaholic.item.items.vapes.swiftness.*;
import com.arta.vapeaholic.item.items.vapes.waterbreathing.*;
import com.arta.vapeaholic.item.items.vapes.weakness.*;
import com.arta.vapeaholic.item.items.vapes.wither.*;
import net.minecraft.item.Item;
import net.minecraftforge.fml.common.registry.ForgeRegistries;

public class ModItems {
	public static final Item BATTERY = registerItem(new Battery("battery"));
	public static final Item COIL = registerItem(new Coil("coil"));
	public static final Item MOUTHPIECE = registerItem(new Mouthpiece("mouthpiece"));

	public static final Item VAPE_POD = registerItem(new VapePod("vape_pod"));
	public static final Item WATER_VAPE_POD = registerItem(new WaterVapePod("water_vape_pod"));
	public static final Item MUNDANE_VAPE_POD = registerItem(new MundaneVapePod("mundane_vape_pod"));
	public static final Item THICK_VAPE_POD = registerItem(new ThickVapePod("thick_vape_pod"));
	public static final Item AWKWARD_VAPE_POD = registerItem(new AwkwardVapePod("awkward_vape_pod"));
	public static final Item FIRE_RESISTANCE_VAPE_POD = registerItem(new FireResistanceVapePod("fire_resistance_vape_pod"));
	public static final Item INSTANT_DAMAGE_VAPE_POD = registerItem(new InstantDamageVapePod("instant_damage_vape_pod"));
	public static final Item INSTANT_HEALTH_VAPE_POD = registerItem(new InstantHealthVapePod("instant_health_vape_pod"));
	public static final Item INVISIBILITY_VAPE_POD = registerItem(new InvisibilityVapePod("invisibility_vape_pod"));
	public static final Item JUMP_BOOST_VAPE_POD = registerItem(new JumpBoostVapePod("jump_boost_vape_pod"));
	public static final Item LUCK_VAPE_POD = registerItem(new LuckVapePod("luck_vape_pod"));
	public static final Item NIGHT_VISION_VAPE_POD = registerItem(new NightVisionVapePod("night_vision_vape_pod"));
	public static final Item POISON_VAPE_POD = registerItem(new PoisonVapePod("poison_vape_pod"));
	public static final Item REGENERATION_VAPE_POD = registerItem(new RegenerationVapePod("regeneration_vape_pod"));
	public static final Item SLOWNESS_VAPE_POD = registerItem(new SlownessVapePod("slowness_vape_pod"));
	public static final Item STRENGTH_VAPE_POD = registerItem(new StrengthVapePod("strength_vape_pod"));
	public static final Item SWIFTNESS_VAPE_POD = registerItem(new SwiftnessVapePod("swiftness_vape_pod"));
	public static final Item WATER_BREATHING_VAPE_POD = registerItem( new WaterBreathingVapePod("water_breathing_vape_pod"));
	public static final Item WEAKNESS_VAPE_POD = registerItem(new WeaknessVapePod("weakness_vape_pod"));
	public static final Item WITHER_VAPE_POD = registerItem(new WitherVapePod("wither_vape_pod"));

	public static final Item RED_VAPE = registerItem(new RedVape("red_vape"));
	public static final Item ORANGE_VAPE = registerItem(new OrangeVape("orange_vape"));
	public static final Item YELLOW_VAPE = registerItem(new YellowVape("yellow_vape"));
	public static final Item LIME_VAPE = registerItem(new LimeVape("lime_vape"));
	public static final Item GREEN_VAPE = registerItem(new GreenVape("green_vape"));
	public static final Item CYAN_VAPE = registerItem(new CyanVape("cyan_vape"));
	public static final Item LIGHT_BLUE_VAPE = registerItem(new LightBlueVape("light_blue_vape"));
	public static final Item BLUE_VAPE = registerItem(new BlueVape("blue_vape"));
	public static final Item PURPLE_VAPE = registerItem(new PurpleVape("purple_vape"));
	public static final Item MAGENTA_VAPE = registerItem(new MagentaVape("magenta_vape"));
	public static final Item PINK_VAPE = registerItem(new PinkVape("pink_vape"));
	public static final Item BROWN_VAPE = registerItem(new BrownVape("brown_vape"));
	public static final Item WHITE_VAPE = registerItem(new WhiteVape("white_vape"));
	public static final Item LIGHT_GRAY_VAPE = registerItem(new LightGrayVape("light_gray_vape"));
	public static final Item GRAY_VAPE = registerItem(new GrayVape("gray_vape"));
	public static final Item BLACK_VAPE = registerItem(new BlackVape("black_vape"));

	public static final Item WATER_RED_VAPE = registerItem(new WaterRedVape("water_red_vape"));
	public static final Item WATER_ORANGE_VAPE = registerItem(new WaterOrangeVape("water_orange_vape"));
	public static final Item WATER_YELLOW_VAPE = registerItem(new WaterYellowVape("water_yellow_vape"));
	public static final Item WATER_LIME_VAPE = registerItem(new WaterLimeVape("water_lime_vape"));
	public static final Item WATER_GREEN_VAPE = registerItem(new WaterGreenVape("water_green_vape"));
	public static final Item WATER_CYAN_VAPE = registerItem(new WaterCyanVape("water_cyan_vape"));
	public static final Item WATER_LIGHT_BLUE_VAPE = registerItem(new WaterLightBlueVape("water_light_blue_vape"));
	public static final Item WATER_BLUE_VAPE = registerItem(new WaterBlueVape("water_blue_vape"));
	public static final Item WATER_PURPLE_VAPE = registerItem(new WaterPurpleVape("water_purple_vape"));
	public static final Item WATER_MAGENTA_VAPE = registerItem(new WaterMagentaVape("water_magenta_vape"));
	public static final Item WATER_PINK_VAPE = registerItem(new WaterPinkVape("water_pink_vape"));
	public static final Item WATER_BROWN_VAPE = registerItem(new WaterBrownVape("water_brown_vape"));
	public static final Item WATER_WHITE_VAPE = registerItem(new WaterWhiteVape("water_white_vape"));
	public static final Item WATER_LIGHT_GRAY_VAPE = registerItem(new WaterLightGrayVape("water_light_gray_vape"));
	public static final Item WATER_GRAY_VAPE = registerItem(new WaterGrayVape("water_gray_vape"));
	public static final Item WATER_BLACK_VAPE = registerItem(new WaterBlackVape("water_black_vape"));

	public static final Item FIRE_RESISTANCE_RED_VAPE = registerItem(new FireResistanceRedVape("fire_resistance_red_vape"));
	public static final Item FIRE_RESISTANCE_ORANGE_VAPE = registerItem(new FireResistanceOrangeVape("fire_resistance_orange_vape"));
	public static final Item FIRE_RESISTANCE_YELLOW_VAPE = registerItem(new FireResistanceYellowVape("fire_resistance_yellow_vape"));
	public static final Item FIRE_RESISTANCE_LIME_VAPE = registerItem(new FireResistanceLimeVape("fire_resistance_lime_vape"));
	public static final Item FIRE_RESISTANCE_GREEN_VAPE = registerItem(new FireResistanceGreenVape("fire_resistance_green_vape"));
	public static final Item FIRE_RESISTANCE_CYAN_VAPE = registerItem(new FireResistanceCyanVape("fire_resistance_cyan_vape"));
	public static final Item FIRE_RESISTANCE_LIGHT_BLUE_VAPE = registerItem(new FireResistanceLightBlueVape("fire_resistance_light_blue_vape"));
	public static final Item FIRE_RESISTANCE_BLUE_VAPE = registerItem(new FireResistanceBlueVape("fire_resistance_blue_vape"));
	public static final Item FIRE_RESISTANCE_PURPLE_VAPE = registerItem(new FireResistancePurpleVape("fire_resistance_purple_vape"));
	public static final Item FIRE_RESISTANCE_MAGENTA_VAPE = registerItem(new FireResistanceMagentaVape("fire_resistance_magenta_vape"));
	public static final Item FIRE_RESISTANCE_PINK_VAPE = registerItem(new FireResistancePinkVape("fire_resistance_pink_vape"));
	public static final Item FIRE_RESISTANCE_BROWN_VAPE = registerItem(new FireResistanceBrownVape("fire_resistance_brown_vape"));
	public static final Item FIRE_RESISTANCE_WHITE_VAPE = registerItem(new FireResistanceWhiteVape("fire_resistance_white_vape"));
	public static final Item FIRE_RESISTANCE_LIGHT_GRAY_VAPE = registerItem(new FireResistanceLightGrayVape("fire_resistance_light_gray_vape"));
	public static final Item FIRE_RESISTANCE_GRAY_VAPE = registerItem(new FireResistanceGrayVape("fire_resistance_gray_vape"));
	public static final Item FIRE_RESISTANCE_BLACK_VAPE = registerItem(new FireResistanceBlackVape("fire_resistance_black_vape"));

	public static final Item INSTANT_DAMAGE_RED_VAPE = registerItem(new InstantDamageRedVape("instant_damage_red_vape"));
	public static final Item INSTANT_DAMAGE_ORANGE_VAPE = registerItem(new InstantDamageOrangeVape("instant_damage_orange_vape"));
	public static final Item INSTANT_DAMAGE_YELLOW_VAPE = registerItem(new InstantDamageYellowVape("instant_damage_yellow_vape"));
	public static final Item INSTANT_DAMAGE_LIME_VAPE = registerItem(new InstantDamageLimeVape("instant_damage_lime_vape"));
	public static final Item INSTANT_DAMAGE_GREEN_VAPE = registerItem(new InstantDamageGreenVape("instant_damage_green_vape"));
	public static final Item INSTANT_DAMAGE_CYAN_VAPE = registerItem(new InstantDamageCyanVape("instant_damage_cyan_vape"));
	public static final Item INSTANT_DAMAGE_LIGHT_BLUE_VAPE = registerItem(new InstantDamageLightBlueVape("instant_damage_light_blue_vape"));
	public static final Item INSTANT_DAMAGE_BLUE_VAPE = registerItem(new InstantDamageBlueVape("instant_damage_blue_vape"));
	public static final Item INSTANT_DAMAGE_PURPLE_VAPE = registerItem(new InstantDamagePurpleVape("instant_damage_purple_vape"));
	public static final Item INSTANT_DAMAGE_MAGENTA_VAPE = registerItem(new InstantDamageMagentaVape("instant_damage_magenta_vape"));
	public static final Item INSTANT_DAMAGE_PINK_VAPE = registerItem(new InstantDamagePinkVape("instant_damage_pink_vape"));
	public static final Item INSTANT_DAMAGE_BROWN_VAPE = registerItem(new InstantDamageBrownVape("instant_damage_brown_vape"));
	public static final Item INSTANT_DAMAGE_WHITE_VAPE = registerItem(new InstantDamageWhiteVape("instant_damage_white_vape"));
	public static final Item INSTANT_DAMAGE_LIGHT_GRAY_VAPE = registerItem(new InstantDamageLightGrayVape("instant_damage_light_gray_vape"));
	public static final Item INSTANT_DAMAGE_GRAY_VAPE = registerItem(new InstantDamageGrayVape("instant_damage_gray_vape"));
	public static final Item INSTANT_DAMAGE_BLACK_VAPE = registerItem(new InstantDamageBlackVape("instant_damage_black_vape"));

	public static final Item INSTANT_HEALTH_RED_VAPE = registerItem(new InstantHealthRedVape("instant_health_red_vape"));
	public static final Item INSTANT_HEALTH_ORANGE_VAPE = registerItem(new InstantHealthOrangeVape("instant_health_orange_vape"));
	public static final Item INSTANT_HEALTH_YELLOW_VAPE = registerItem(new InstantHealthYellowVape("instant_health_yellow_vape"));
	public static final Item INSTANT_HEALTH_LIME_VAPE = registerItem(new InstantHealthLimeVape("instant_health_lime_vape"));
	public static final Item INSTANT_HEALTH_GREEN_VAPE = registerItem(new InstantHealthGreenVape("instant_health_green_vape"));
	public static final Item INSTANT_HEALTH_CYAN_VAPE = registerItem(new InstantHealthCyanVape("instant_health_cyan_vape"));
	public static final Item INSTANT_HEALTH_LIGHT_BLUE_VAPE = registerItem(new InstantHealthLightBlueVape("instant_health_light_blue_vape"));
	public static final Item INSTANT_HEALTH_BLUE_VAPE = registerItem(new InstantHealthBlueVape("instant_health_blue_vape"));
	public static final Item INSTANT_HEALTH_PURPLE_VAPE = registerItem(new InstantHealthPurpleVape("instant_health_purple_vape"));
	public static final Item INSTANT_HEALTH_MAGENTA_VAPE = registerItem(new InstantHealthMagentaVape("instant_health_magenta_vape"));
	public static final Item INSTANT_HEALTH_PINK_VAPE = registerItem(new InstantHealthPinkVape("instant_health_pink_vape"));
	public static final Item INSTANT_HEALTH_BROWN_VAPE = registerItem(new InstantHealthBrownVape("instant_health_brown_vape"));
	public static final Item INSTANT_HEALTH_WHITE_VAPE = registerItem(new InstantHealthWhiteVape("instant_health_white_vape"));
	public static final Item INSTANT_HEALTH_LIGHT_GRAY_VAPE = registerItem(new InstantHealthLightGrayVape("instant_health_light_gray_vape"));
	public static final Item INSTANT_HEALTH_GRAY_VAPE = registerItem(new InstantHealthGrayVape("instant_health_gray_vape"));
	public static final Item INSTANT_HEALTH_BLACK_VAPE = registerItem(new InstantHealthBlackVape("instant_health_black_vape"));

	public static final Item INVISIBILITY_RED_VAPE = registerItem(new InvisibilityRedVape("invisibility_red_vape"));
	public static final Item INVISIBILITY_ORANGE_VAPE = registerItem(new InvisibilityOrangeVape("invisibility_orange_vape"));
	public static final Item INVISIBILITY_YELLOW_VAPE = registerItem(new InvisibilityYellowVape("invisibility_yellow_vape"));
	public static final Item INVISIBILITY_LIME_VAPE = registerItem(new InvisibilityLimeVape("invisibility_lime_vape"));
	public static final Item INVISIBILITY_GREEN_VAPE = registerItem(new InvisibilityGreenVape("invisibility_green_vape"));
	public static final Item INVISIBILITY_CYAN_VAPE = registerItem(new InvisibilityCyanVape("invisibility_cyan_vape"));
	public static final Item INVISIBILITY_LIGHT_BLUE_VAPE = registerItem(new InvisibilityLightBlueVape("invisibility_light_blue_vape"));
	public static final Item INVISIBILITY_BLUE_VAPE = registerItem(new InvisibilityBlueVape("invisibility_blue_vape"));
	public static final Item INVISIBILITY_PURPLE_VAPE = registerItem(new InvisibilityPurpleVape("invisibility_purple_vape"));
	public static final Item INVISIBILITY_MAGENTA_VAPE = registerItem(new InvisibilityMagentaVape("invisibility_magenta_vape"));
	public static final Item INVISIBILITY_PINK_VAPE = registerItem(new InvisibilityPinkVape("invisibility_pink_vape"));
	public static final Item INVISIBILITY_BROWN_VAPE = registerItem(new InvisibilityBrownVape("invisibility_brown_vape"));
	public static final Item INVISIBILITY_WHITE_VAPE = registerItem(new InvisibilityWhiteVape("invisibility_white_vape"));
	public static final Item INVISIBILITY_LIGHT_GRAY_VAPE = registerItem(new InvisibilityLightGrayVape("invisibility_light_gray_vape"));
	public static final Item INVISIBILITY_GRAY_VAPE = registerItem(new InvisibilityGrayVape("invisibility_gray_vape"));
	public static final Item INVISIBILITY_BLACK_VAPE = registerItem(new InvisibilityBlackVape("invisibility_black_vape"));

	public static final Item JUMP_BOOST_RED_VAPE = registerItem(new JumpBoostRedVape("jump_boost_red_vape"));
	public static final Item JUMP_BOOST_ORANGE_VAPE = registerItem(new JumpBoostOrangeVape("jump_boost_orange_vape"));
	public static final Item JUMP_BOOST_YELLOW_VAPE = registerItem(new JumpBoostYellowVape("jump_boost_yellow_vape"));
	public static final Item JUMP_BOOST_LIME_VAPE = registerItem(new JumpBoostLimeVape("jump_boost_lime_vape"));
	public static final Item JUMP_BOOST_GREEN_VAPE = registerItem(new JumpBoostGreenVape("jump_boost_green_vape"));
	public static final Item JUMP_BOOST_CYAN_VAPE = registerItem(new JumpBoostCyanVape("jump_boost_cyan_vape"));
	public static final Item JUMP_BOOST_LIGHT_BLUE_VAPE = registerItem(new JumpBoostLightBlueVape("jump_boost_light_blue_vape"));
	public static final Item JUMP_BOOST_BLUE_VAPE = registerItem(new JumpBoostBlueVape("jump_boost_blue_vape"));
	public static final Item JUMP_BOOST_PURPLE_VAPE = registerItem(new JumpBoostPurpleVape("jump_boost_purple_vape"));
	public static final Item JUMP_BOOST_MAGENTA_VAPE = registerItem(new JumpBoostMagentaVape("jump_boost_magenta_vape"));
	public static final Item JUMP_BOOST_PINK_VAPE = registerItem(new JumpBoostPinkVape("jump_boost_pink_vape"));
	public static final Item JUMP_BOOST_BROWN_VAPE = registerItem(new JumpBoostBrownVape("jump_boost_brown_vape"));
	public static final Item JUMP_BOOST_WHITE_VAPE = registerItem(new JumpBoostWhiteVape("jump_boost_white_vape"));
	public static final Item JUMP_BOOST_LIGHT_GRAY_VAPE = registerItem(new JumpBoostLightGrayVape("jump_boost_light_gray_vape"));
	public static final Item JUMP_BOOST_GRAY_VAPE = registerItem(new JumpBoostGrayVape("jump_boost_gray_vape"));
	public static final Item JUMP_BOOST_BLACK_VAPE = registerItem(new JumpBoostBlackVape("jump_boost_black_vape"));

	public static final Item LUCK_RED_VAPE = registerItem(new LuckRedVape("luck_red_vape"));
	public static final Item LUCK_ORANGE_VAPE = registerItem(new LuckOrangeVape("luck_orange_vape"));
	public static final Item LUCK_YELLOW_VAPE = registerItem(new LuckYellowVape("luck_yellow_vape"));
	public static final Item LUCK_LIME_VAPE = registerItem(new LuckLimeVape("luck_lime_vape"));
	public static final Item LUCK_GREEN_VAPE = registerItem(new LuckGreenVape("luck_green_vape"));
	public static final Item LUCK_CYAN_VAPE = registerItem(new LuckCyanVape("luck_cyan_vape"));
	public static final Item LUCK_LIGHT_BLUE_VAPE = registerItem(new LuckLightBlueVape("luck_light_blue_vape"));
	public static final Item LUCK_BLUE_VAPE = registerItem(new LuckBlueVape("luck_blue_vape"));
	public static final Item LUCK_PURPLE_VAPE = registerItem(new LuckPurpleVape("luck_purple_vape"));
	public static final Item LUCK_MAGENTA_VAPE = registerItem(new LuckMagentaVape("luck_magenta_vape"));
	public static final Item LUCK_PINK_VAPE = registerItem(new LuckPinkVape("luck_pink_vape"));
	public static final Item LUCK_BROWN_VAPE = registerItem(new LuckBrownVape("luck_brown_vape"));
	public static final Item LUCK_WHITE_VAPE = registerItem(new LuckWhiteVape("luck_white_vape"));
	public static final Item LUCK_LIGHT_GRAY_VAPE = registerItem(new LuckLightGrayVape("luck_light_gray_vape"));
	public static final Item LUCK_GRAY_VAPE = registerItem(new LuckGrayVape("luck_gray_vape"));
	public static final Item LUCK_BLACK_VAPE = registerItem(new LuckBlackVape("luck_black_vape"));

	public static final Item NIGHT_VISION_RED_VAPE = registerItem(new NightVisionRedVape("night_vision_red_vape"));
	public static final Item NIGHT_VISION_ORANGE_VAPE = registerItem(new NightVisionOrangeVape("night_vision_orange_vape"));
	public static final Item NIGHT_VISION_YELLOW_VAPE = registerItem(new NightVisionYellowVape("night_vision_yellow_vape"));
	public static final Item NIGHT_VISION_LIME_VAPE = registerItem(new NightVisionLimeVape("night_vision_lime_vape"));
	public static final Item NIGHT_VISION_GREEN_VAPE = registerItem(new NightVisionGreenVape("night_vision_green_vape"));
	public static final Item NIGHT_VISION_CYAN_VAPE = registerItem(new NightVisionCyanVape("night_vision_cyan_vape"));
	public static final Item NIGHT_VISION_LIGHT_BLUE_VAPE = registerItem(new NightVisionLightBlueVape("night_vision_light_blue_vape"));
	public static final Item NIGHT_VISION_BLUE_VAPE = registerItem(new NightVisionBlueVape("night_vision_blue_vape"));
	public static final Item NIGHT_VISION_PURPLE_VAPE = registerItem(new NightVisionPurpleVape("night_vision_purple_vape"));
	public static final Item NIGHT_VISION_MAGENTA_VAPE = registerItem(new NightVisionMagentaVape("night_vision_magenta_vape"));
	public static final Item NIGHT_VISION_PINK_VAPE = registerItem(new NightVisionPinkVape("night_vision_pink_vape"));
	public static final Item NIGHT_VISION_BROWN_VAPE = registerItem(new NightVisionBrownVape("night_vision_brown_vape"));
	public static final Item NIGHT_VISION_WHITE_VAPE = registerItem(new NightVisionWhiteVape("night_vision_white_vape"));
	public static final Item NIGHT_VISION_LIGHT_GRAY_VAPE = registerItem(new NightVisionLightGrayVape("night_vision_light_gray_vape"));
	public static final Item NIGHT_VISION_GRAY_VAPE = registerItem(new NightVisionGrayVape("night_vision_gray_vape"));
	public static final Item NIGHT_VISION_BLACK_VAPE = registerItem(new NightVisionBlackVape("night_vision_black_vape"));

	public static final Item POISON_RED_VAPE = registerItem(new PoisonRedVape("poison_red_vape"));
	public static final Item POISON_ORANGE_VAPE = registerItem(new PoisonOrangeVape("poison_orange_vape"));
	public static final Item POISON_YELLOW_VAPE = registerItem(new PoisonYellowVape("poison_yellow_vape"));
	public static final Item POISON_LIME_VAPE = registerItem(new PoisonLimeVape("poison_lime_vape"));
	public static final Item POISON_GREEN_VAPE = registerItem(new PoisonGreenVape("poison_green_vape"));
	public static final Item POISON_CYAN_VAPE = registerItem(new PoisonCyanVape("poison_cyan_vape"));
	public static final Item POISON_LIGHT_BLUE_VAPE = registerItem(new PoisonLightBlueVape("poison_light_blue_vape"));
	public static final Item POISON_BLUE_VAPE = registerItem(new PoisonBlueVape("poison_blue_vape"));
	public static final Item POISON_PURPLE_VAPE = registerItem(new PoisonPurpleVape("poison_purple_vape"));
	public static final Item POISON_MAGENTA_VAPE = registerItem(new PoisonMagentaVape("poison_magenta_vape"));
	public static final Item POISON_PINK_VAPE = registerItem(new PoisonPinkVape("poison_pink_vape"));
	public static final Item POISON_BROWN_VAPE = registerItem(new PoisonBrownVape("poison_brown_vape"));
	public static final Item POISON_WHITE_VAPE = registerItem(new PoisonWhiteVape("poison_white_vape"));
	public static final Item POISON_LIGHT_GRAY_VAPE = registerItem(new PoisonLightGrayVape("poison_light_gray_vape"));
	public static final Item POISON_GRAY_VAPE = registerItem(new PoisonGrayVape("poison_gray_vape"));
	public static final Item POISON_BLACK_VAPE = registerItem(new PoisonBlackVape("poison_black_vape"));

	public static final Item REGENERATION_RED_VAPE = registerItem(new RegenerationRedVape("regeneration_red_vape"));
	public static final Item REGENERATION_ORANGE_VAPE = registerItem(new RegenerationOrangeVape("regeneration_orange_vape"));
	public static final Item REGENERATION_YELLOW_VAPE = registerItem(new RegenerationYellowVape("regeneration_yellow_vape"));
	public static final Item REGENERATION_LIME_VAPE = registerItem(new RegenerationLimeVape("regeneration_lime_vape"));
	public static final Item REGENERATION_GREEN_VAPE = registerItem(new RegenerationGreenVape("regeneration_green_vape"));
	public static final Item REGENERATION_CYAN_VAPE = registerItem(new RegenerationCyanVape("regeneration_cyan_vape"));
	public static final Item REGENERATION_LIGHT_BLUE_VAPE = registerItem(new RegenerationLightBlueVape("regeneration_light_blue_vape"));
	public static final Item REGENERATION_BLUE_VAPE = registerItem(new RegenerationBlueVape("regeneration_blue_vape"));
	public static final Item REGENERATION_PURPLE_VAPE = registerItem(new RegenerationPurpleVape("regeneration_purple_vape"));
	public static final Item REGENERATION_MAGENTA_VAPE = registerItem(new RegenerationMagentaVape("regeneration_magenta_vape"));
	public static final Item REGENERATION_PINK_VAPE = registerItem(new RegenerationPinkVape("regeneration_pink_vape"));
	public static final Item REGENERATION_BROWN_VAPE = registerItem(new RegenerationBrownVape("regeneration_brown_vape"));
	public static final Item REGENERATION_WHITE_VAPE = registerItem(new RegenerationWhiteVape("regeneration_white_vape"));
	public static final Item REGENERATION_LIGHT_GRAY_VAPE = registerItem(new RegenerationLightGrayVape("regeneration_light_gray_vape"));
	public static final Item REGENERATION_GRAY_VAPE = registerItem(new RegenerationGrayVape("regeneration_gray_vape"));
	public static final Item REGENERATION_BLACK_VAPE = registerItem(new RegenerationBlackVape("regeneration_black_vape"));

	public static final Item SLOWNESS_RED_VAPE = registerItem(new SlownessRedVape("slowness_red_vape"));
	public static final Item SLOWNESS_ORANGE_VAPE = registerItem(new SlownessOrangeVape("slowness_orange_vape"));
	public static final Item SLOWNESS_YELLOW_VAPE = registerItem(new SlownessYellowVape("slowness_yellow_vape"));
	public static final Item SLOWNESS_LIME_VAPE = registerItem(new SlownessLimeVape("slowness_lime_vape"));
	public static final Item SLOWNESS_GREEN_VAPE = registerItem(new SlownessGreenVape("slowness_green_vape"));
	public static final Item SLOWNESS_CYAN_VAPE = registerItem(new SlownessCyanVape("slowness_cyan_vape"));
	public static final Item SLOWNESS_LIGHT_BLUE_VAPE = registerItem(new SlownessLightBlueVape("slowness_light_blue_vape"));
	public static final Item SLOWNESS_BLUE_VAPE = registerItem(new SlownessBlueVape("slowness_blue_vape"));
	public static final Item SLOWNESS_PURPLE_VAPE = registerItem(new SlownessPurpleVape("slowness_purple_vape"));
	public static final Item SLOWNESS_MAGENTA_VAPE = registerItem(new SlownessMagentaVape("slowness_magenta_vape"));
	public static final Item SLOWNESS_PINK_VAPE = registerItem(new SlownessPinkVape("slowness_pink_vape"));
	public static final Item SLOWNESS_BROWN_VAPE = registerItem(new SlownessBrownVape("slowness_brown_vape"));
	public static final Item SLOWNESS_WHITE_VAPE = registerItem(new SlownessWhiteVape("slowness_white_vape"));
	public static final Item SLOWNESS_LIGHT_GRAY_VAPE = registerItem(new SlownessLightGrayVape("slowness_light_gray_vape"));
	public static final Item SLOWNESS_GRAY_VAPE = registerItem(new SlownessGrayVape("slowness_gray_vape"));
	public static final Item SLOWNESS_BLACK_VAPE = registerItem(new SlownessBlackVape("slowness_black_vape"));

	public static final Item STRENGTH_RED_VAPE = registerItem(new StrengthRedVape("strength_red_vape"));
	public static final Item STRENGTH_ORANGE_VAPE = registerItem(new StrengthOrangeVape("strength_orange_vape"));
	public static final Item STRENGTH_YELLOW_VAPE = registerItem(new StrengthYellowVape("strength_yellow_vape"));
	public static final Item STRENGTH_LIME_VAPE = registerItem(new StrengthLimeVape("strength_lime_vape"));
	public static final Item STRENGTH_GREEN_VAPE = registerItem(new StrengthGreenVape("strength_green_vape"));
	public static final Item STRENGTH_CYAN_VAPE = registerItem(new StrengthCyanVape("strength_cyan_vape"));
	public static final Item STRENGTH_LIGHT_BLUE_VAPE = registerItem(new StrengthLightBlueVape("strength_light_blue_vape"));
	public static final Item STRENGTH_BLUE_VAPE = registerItem(new StrengthBlueVape("strength_blue_vape"));
	public static final Item STRENGTH_PURPLE_VAPE = registerItem(new StrengthPurpleVape("strength_purple_vape"));
	public static final Item STRENGTH_MAGENTA_VAPE = registerItem(new StrengthMagentaVape("strength_magenta_vape"));
	public static final Item STRENGTH_PINK_VAPE = registerItem(new StrengthPinkVape("strength_pink_vape"));
	public static final Item STRENGTH_BROWN_VAPE = registerItem(new StrengthBrownVape("strength_brown_vape"));
	public static final Item STRENGTH_WHITE_VAPE = registerItem(new StrengthWhiteVape("strength_white_vape"));
	public static final Item STRENGTH_LIGHT_GRAY_VAPE = registerItem(new StrengthLightGrayVape("strength_light_gray_vape"));
	public static final Item STRENGTH_GRAY_VAPE = registerItem(new StrengthGrayVape("strength_gray_vape"));
	public static final Item STRENGTH_BLACK_VAPE = registerItem(new StrengthBlackVape("strength_black_vape"));

	public static final Item SWIFTNESS_RED_VAPE = registerItem(new SwiftnessRedVape("swiftness_red_vape"));
	public static final Item SWIFTNESS_ORANGE_VAPE = registerItem(new SwiftnessOrangeVape("swiftness_orange_vape"));
	public static final Item SWIFTNESS_YELLOW_VAPE = registerItem(new SwiftnessYellowVape("swiftness_yellow_vape"));
	public static final Item SWIFTNESS_LIME_VAPE = registerItem(new SwiftnessLimeVape("swiftness_lime_vape"));
	public static final Item SWIFTNESS_GREEN_VAPE = registerItem(new SwiftnessGreenVape("swiftness_green_vape"));
	public static final Item SWIFTNESS_CYAN_VAPE = registerItem(new SwiftnessCyanVape("swiftness_cyan_vape"));
	public static final Item SWIFTNESS_LIGHT_BLUE_VAPE = registerItem(new SwiftnessLightBlueVape("swiftness_light_blue_vape"));
	public static final Item SWIFTNESS_BLUE_VAPE = registerItem(new SwiftnessBlueVape("swiftness_blue_vape"));
	public static final Item SWIFTNESS_PURPLE_VAPE = registerItem(new SwiftnessPurpleVape("swiftness_purple_vape"));
	public static final Item SWIFTNESS_MAGENTA_VAPE = registerItem(new SwiftnessMagentaVape("swiftness_magenta_vape"));
	public static final Item SWIFTNESS_PINK_VAPE = registerItem(new SwiftnessPinkVape("swiftness_pink_vape"));
	public static final Item SWIFTNESS_BROWN_VAPE = registerItem(new SwiftnessBrownVape("swiftness_brown_vape"));
	public static final Item SWIFTNESS_WHITE_VAPE = registerItem(new SwiftnessWhiteVape("swiftness_white_vape"));
	public static final Item SWIFTNESS_LIGHT_GRAY_VAPE = registerItem(new SwiftnessLightGrayVape("swiftness_light_gray_vape"));
	public static final Item SWIFTNESS_GRAY_VAPE = registerItem(new SwiftnessGrayVape("swiftness_gray_vape"));
	public static final Item SWIFTNESS_BLACK_VAPE = registerItem(new SwiftnessBlackVape("swiftness_black_vape"));

	public static final Item WATER_BREATHING_RED_VAPE = registerItem(new WaterBreathingRedVape("water_breathing_red_vape"));
	public static final Item WATER_BREATHING_ORANGE_VAPE = registerItem(new WaterBreathingOrangeVape("water_breathing_orange_vape"));
	public static final Item WATER_BREATHING_YELLOW_VAPE = registerItem(new WaterBreathingYellowVape("water_breathing_yellow_vape"));
	public static final Item WATER_BREATHING_LIME_VAPE = registerItem(new WaterBreathingLimeVape("water_breathing_lime_vape"));
	public static final Item WATER_BREATHING_GREEN_VAPE = registerItem(new WaterBreathingGreenVape("water_breathing_green_vape"));
	public static final Item WATER_BREATHING_CYAN_VAPE = registerItem(new WaterBreathingCyanVape("water_breathing_cyan_vape"));
	public static final Item WATER_BREATHING_LIGHT_BLUE_VAPE = registerItem(new WaterBreathingLightBlueVape("water_breathing_light_blue_vape"));
	public static final Item WATER_BREATHING_BLUE_VAPE = registerItem(new WaterBreathingBlueVape("water_breathing_blue_vape"));
	public static final Item WATER_BREATHING_PURPLE_VAPE = registerItem(new WaterBreathingPurpleVape("water_breathing_purple_vape"));
	public static final Item WATER_BREATHING_MAGENTA_VAPE = registerItem(new WaterBreathingMagentaVape("water_breathing_magenta_vape"));
	public static final Item WATER_BREATHING_PINK_VAPE = registerItem(new WaterBreathingPinkVape("water_breathing_pink_vape"));
	public static final Item WATER_BREATHING_BROWN_VAPE = registerItem(new WaterBreathingBrownVape("water_breathing_brown_vape"));
	public static final Item WATER_BREATHING_WHITE_VAPE = registerItem(new WaterBreathingWhiteVape("water_breathing_white_vape"));
	public static final Item WATER_BREATHING_LIGHT_GRAY_VAPE = registerItem(new WaterBreathingLightGrayVape("water_breathing_light_gray_vape"));
	public static final Item WATER_BREATHING_GRAY_VAPE = registerItem(new WaterBreathingGrayVape("water_breathing_gray_vape"));
	public static final Item WATER_BREATHING_BLACK_VAPE = registerItem(new WaterBreathingBlackVape("water_breathing_black_vape"));

	public static final Item WEAKNESS_RED_VAPE = registerItem(new WeaknessRedVape("weakness_red_vape"));
	public static final Item WEAKNESS_ORANGE_VAPE = registerItem(new WeaknessOrangeVape("weakness_orange_vape"));
	public static final Item WEAKNESS_YELLOW_VAPE = registerItem(new WeaknessYellowVape("weakness_yellow_vape"));
	public static final Item WEAKNESS_LIME_VAPE = registerItem(new WeaknessLimeVape("weakness_lime_vape"));
	public static final Item WEAKNESS_GREEN_VAPE = registerItem(new WeaknessGreenVape("weakness_green_vape"));
	public static final Item WEAKNESS_CYAN_VAPE = registerItem(new WeaknessCyanVape("weakness_cyan_vape"));
	public static final Item WEAKNESS_LIGHT_BLUE_VAPE = registerItem(new WeaknessLightBlueVape("weakness_light_blue_vape"));
	public static final Item WEAKNESS_BLUE_VAPE = registerItem(new WeaknessBlueVape("weakness_blue_vape"));
	public static final Item WEAKNESS_PURPLE_VAPE = registerItem(new WeaknessPurpleVape("weakness_purple_vape"));
	public static final Item WEAKNESS_MAGENTA_VAPE = registerItem(new WeaknessMagentaVape("weakness_magenta_vape"));
	public static final Item WEAKNESS_PINK_VAPE = registerItem(new WeaknessPinkVape("weakness_pink_vape"));
	public static final Item WEAKNESS_BROWN_VAPE = registerItem(new WeaknessBrownVape("weakness_brown_vape"));
	public static final Item WEAKNESS_WHITE_VAPE = registerItem(new WeaknessWhiteVape("weakness_white_vape"));
	public static final Item WEAKNESS_LIGHT_GRAY_VAPE = registerItem(new WeaknessLightGrayVape("weakness_light_gray_vape"));
	public static final Item WEAKNESS_GRAY_VAPE = registerItem(new WeaknessGrayVape("weakness_gray_vape"));
	public static final Item WEAKNESS_BLACK_VAPE = registerItem(new WeaknessBlackVape("weakness_black_vape"));

	public static final Item WITHER_RED_VAPE = registerItem(new WitherRedVape("wither_red_vape"));
	public static final Item WITHER_ORANGE_VAPE = registerItem(new WitherOrangeVape("wither_orange_vape"));
	public static final Item WITHER_YELLOW_VAPE = registerItem(new WitherYellowVape("wither_yellow_vape"));
	public static final Item WITHER_LIME_VAPE = registerItem(new WitherLimeVape("wither_lime_vape"));
	public static final Item WITHER_GREEN_VAPE = registerItem(new WitherGreenVape("wither_green_vape"));
	public static final Item WITHER_CYAN_VAPE = registerItem(new WitherCyanVape("wither_cyan_vape"));
	public static final Item WITHER_LIGHT_BLUE_VAPE = registerItem(new WitherLightBlueVape("wither_light_blue_vape"));
	public static final Item WITHER_BLUE_VAPE = registerItem(new WitherBlueVape("wither_blue_vape"));
	public static final Item WITHER_PURPLE_VAPE = registerItem(new WitherPurpleVape("wither_purple_vape"));
	public static final Item WITHER_MAGENTA_VAPE = registerItem(new WitherMagentaVape("wither_magenta_vape"));
	public static final Item WITHER_PINK_VAPE = registerItem(new WitherPinkVape("wither_pink_vape"));
	public static final Item WITHER_BROWN_VAPE = registerItem(new WitherBrownVape("wither_brown_vape"));
	public static final Item WITHER_WHITE_VAPE = registerItem(new WitherWhiteVape("wither_white_vape"));
	public static final Item WITHER_LIGHT_GRAY_VAPE = registerItem(new WitherLightGrayVape("wither_light_gray_vape"));
	public static final Item WITHER_GRAY_VAPE = registerItem(new WitherGrayVape("wither_gray_vape"));
	public static final Item WITHER_BLACK_VAPE = registerItem(new WitherBlackVape("wither_black_vape"));


	private static Item registerItem(Item item) {
		ForgeRegistries.ITEMS.register(item);
		return item;
	}

	public static void registerModItems() {
		Vapeaholic.LOGGER.info("Registering Mod Items for " + Vapeaholic.MOD_ID);
	}
}
